# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-10 15:48
from __future__ import unicode_literals

import cameradb.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_duration', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('house_number', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('direction', models.CharField(max_length=2, validators=[cameradb.models.validate_direction])),
                ('camera', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='cameradb.Camera')),
            ],
        ),
        migrations.AddField(
            model_name='owner',
            name='camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cameradb.Camera'),
        ),
    ]
