# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 19:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cameradb', '0002_auto_20170711_1824'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='cameras',
            new_name='camera',
        ),
    ]
