# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 20:04
from __future__ import unicode_literals

import cameradb.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cameradb', '0003_auto_20170711_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='direction',
        ),
        migrations.AddField(
            model_name='camera',
            name='direction',
            field=models.CharField(default='NW', max_length=2, validators=[cameradb.models.validate_direction]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='location',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='location',
            name='camera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cameradb.Camera'),
        ),
    ]
