# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-11 20:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cameradb', '0004_auto_20170711_2004'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='camera',
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cameradb.Location'),
        ),
    ]
